-- Run this entire file in Supabase Dashboard → SQL Editor → Run
-- Project: https://supabase.com/dashboard/project/_/sql

-- ============ PROFILES ============
CREATE TABLE IF NOT EXISTS public.profiles (
  id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  updated_at timestamptz,
  username text,
  full_name text,
  avatar_url text,
  website text,
  "group" text NOT NULL DEFAULT 'user',
  expo_push_token text,
  stripe_customer_id text,
  CONSTRAINT username_length CHECK (char_length(username) >= 3 OR username IS NULL)
);

-- ============ RESTAURANTS ============
CREATE TABLE IF NOT EXISTS public.restaurants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text NOT NULL,
  image text,
  delivery_fee real DEFAULT 0 NOT NULL,
  rating real DEFAULT 4.5 NOT NULL
);

-- ============ PRODUCTS ============
CREATE TABLE IF NOT EXISTS public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text NOT NULL,
  image text,
  price real NOT NULL,
  description text,
  restaurant_id bigint REFERENCES public.restaurants(id) ON DELETE SET NULL
);

-- ============ ORDERS ============
CREATE TABLE IF NOT EXISTS public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  status text DEFAULT 'New' NOT NULL,
  total double precision DEFAULT 0 NOT NULL,
  user_id uuid REFERENCES public.profiles(id) ON DELETE CASCADE
);

-- ============ ORDER ITEMS ============
CREATE TABLE IF NOT EXISTS public.order_items (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  size text DEFAULT 'M' NOT NULL,
  quantity integer DEFAULT 1 NOT NULL,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE
);

-- ============ NEW USER TRIGGER ============
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, avatar_url, "group")
  VALUES (
    new.id,
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url',
    coalesce(nullif(lower(trim(new.raw_user_meta_data->>'group')), ''), 'user')
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- ============ SEED RESTAURANTS ============
INSERT INTO public.restaurants (name, image, delivery_fee, rating)
SELECT * FROM (VALUES
  ('Mario''s Pizza', 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/food/peperoni.png', 2.99::real, 4.8::real),
  ('Burger House', 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/food/deluxe.png', 1.99::real, 4.5::real),
  ('Sushi Express', 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/food/veggie.png', 3.49::real, 4.7::real)
) AS v(name, image, delivery_fee, rating)
WHERE NOT EXISTS (SELECT 1 FROM public.restaurants LIMIT 1);

-- ============ RLS ============
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.order_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "profiles_select" ON public.profiles;
CREATE POLICY "profiles_select" ON public.profiles FOR SELECT TO authenticated, anon USING (true);

DROP POLICY IF EXISTS "profiles_insert_own" ON public.profiles;
CREATE POLICY "profiles_insert_own" ON public.profiles FOR INSERT TO authenticated
  WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own" ON public.profiles FOR UPDATE TO authenticated
  USING (auth.uid() = id);

DROP POLICY IF EXISTS "restaurants_read" ON public.restaurants;
CREATE POLICY "restaurants_read" ON public.restaurants FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "products_read" ON public.products;
CREATE POLICY "products_read" ON public.products FOR SELECT TO authenticated USING (true);

DROP POLICY IF EXISTS "products_admin" ON public.products;
CREATE POLICY "products_admin" ON public.products FOR ALL TO authenticated
  USING (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND lower(p."group") = 'admin'))
  WITH CHECK (EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND lower(p."group") = 'admin'));

DROP POLICY IF EXISTS "orders_user_read" ON public.orders;
CREATE POLICY "orders_user_read" ON public.orders FOR SELECT TO authenticated
  USING (
    user_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND lower(p."group") = 'admin')
  );

DROP POLICY IF EXISTS "orders_user_insert" ON public.orders;
CREATE POLICY "orders_user_insert" ON public.orders FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "orders_update" ON public.orders;
CREATE POLICY "orders_update" ON public.orders FOR UPDATE TO authenticated
  USING (
    user_id = auth.uid()
    OR EXISTS (SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND lower(p."group") = 'admin')
  );

DROP POLICY IF EXISTS "order_items_all" ON public.order_items;
CREATE POLICY "order_items_all" ON public.order_items FOR ALL TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_items.order_id
        AND (o.user_id = auth.uid() OR EXISTS (
          SELECT 1 FROM public.profiles p WHERE p.id = auth.uid() AND lower(p."group") = 'admin'
        ))
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_items.order_id AND o.user_id = auth.uid()
    )
  );

-- Backfill profile for existing auth users
INSERT INTO public.profiles (id, "group")
SELECT id, 'user' FROM auth.users
ON CONFLICT (id) DO NOTHING;

-- Make yourself admin (replace email):
-- UPDATE public.profiles SET "group" = 'admin' WHERE id = (SELECT id FROM auth.users WHERE email = 'ambika@gmail.com');

NOTIFY pgrst, 'reload schema';
