-- Restaurants + link products to restaurants.

CREATE TABLE IF NOT EXISTS public.restaurants (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at timestamptz DEFAULT now() NOT NULL,
  name text NOT NULL,
  image text,
  delivery_fee real DEFAULT 0 NOT NULL,
  rating real DEFAULT 4.5 NOT NULL
);

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS restaurant_id bigint REFERENCES public.restaurants(id) ON DELETE SET NULL;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS description text;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.restaurants LIMIT 1) THEN
    INSERT INTO public.restaurants (name, image, delivery_fee, rating) VALUES
      ('Mario''s Pizza', 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/food/peperoni.png', 2.99, 4.8),
      ('Burger House', 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/food/deluxe.png', 1.99, 4.5),
      ('Sushi Express', 'https://notjustdev-dummy.s3.us-east-2.amazonaws.com/food/veggie.png', 3.49, 4.7);
  END IF;
END $$;

-- Attach existing products to the first restaurant when unassigned.
UPDATE public.products
SET restaurant_id = (SELECT id FROM public.restaurants ORDER BY id LIMIT 1)
WHERE restaurant_id IS NULL;

ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone authenticated can read restaurants" ON public.restaurants;
DROP POLICY IF EXISTS "Admins manage restaurants" ON public.restaurants;

CREATE POLICY "Anyone authenticated can read restaurants"
  ON public.restaurants
  FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Admins manage restaurants"
  ON public.restaurants
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND lower(profiles."group") = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.profiles
      WHERE profiles.id = auth.uid()
        AND lower(profiles."group") = 'admin'
    )
  );
